version: '3.8'
services:
  redis:
    image: redis
    ports:
      - "6479:6379"
  funlinks:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      - REDIS_TYPE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8100:8000"
    depends_on:
      - redis